apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-api
  namespace: default
spec:
  gatewayClassName: istio
  infrastructure:
    labels:
      app: istio-gateway
    parametersRef:
      group: ""
      kind: ConfigMap
      name: gateway-config  
  # Only Routes from the same namespace are allowed.
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same  #or All or Selector
    
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: secret-tls
            namespace: default
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:

  deployment: |
    metadata:
      annotations:
        gateway-default-setting: test
    spec:
      replicas: 3

  service: |
    spec:
      type: ClusterIP