apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shopping-api
  namespace: shopping
subjects:
- kind: ServiceAccount
  name: shopping-api
roleRef:
  kind: Role
  name: shopping-api
  apiGroup: rbac.authorization.k8s.io