apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: example-app-1
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/eliedebons/docker-development-youtube-series