on:
  push:
    branches: [ datree ]
  pull_request:
    branches: [ datree ]
    
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 

jobs:
  k8sPolicyCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run Datree Policy Check
        uses: datreeio/action-datree@main
        with:
          path: 'kubernetes/tutorials/basics/yaml/*'
          cliArguments: '--only-k8s-files'