apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}"
data:
  config.json: |
    {
      "environment" : "dev"
    }
# kubectl create configmap example-config --from-file ./golang/configs/config.json
