apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-app
  namespace: default
spec:
  dnsNames:
    - test.marceldempers.dev
  secretName: secret-tls
  issuerRef:
    name: letsencrypt-issuer-ingress
    kind: ClusterIssuer