apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer-gatewayapi
spec:
  acme:
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: gateway-api
                namespace: default
                kind: Gateway