apiVersion: v1
kind: Service
metadata:
  name: daemonset-svc-clusterip
spec:
  type: ClusterIP
  selector:
    name: daemonset-communicate
  ports:
    - protocol: TCP
      name: "http"
      port: 80
      targetPort: 80