global:
  scrape_interval: 15s

#Option A: Prometheus to scrape metrics from Otel
# scrape_configs:
#   - job_name: 'otel-collector'
#     static_configs:
#       - targets: ['otel-collector:9464']