apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: application-cpu
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       application-cpu
  updatePolicy:
    updateMode: "Off"