apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: gateway-client-settings2
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway-api
  keepAlive:
    requests: 5