apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: videos-web
spec:
  hosts:
  - servicemesh.demo
  http:
  - route:
    - destination:
        host: videos-web-v2
      weight: 50
    - destination:
        host: videos-web
      weight: 50